Repository ayeshaa63/c10-lmnh-plants-project, pull requests merged in 2024-04, with the labels that each got.

#33 Transform script including tests
  .gitignore
  etl-script/conftest.py
  etl-script/requirements.txt
  etl-script/test_transform.py
  etl-script/transform.py
  requirements.txt
Labels: enhancement

#44 Error handling for transform and Check the speed.
  etl-script/extract.py
  etl-script/transform.py
Labels: enhancement

#46 added plant name to tranform.py and added an email alert for sensor f…
  etl-script/conftest.py
  etl-script/email_alert.py
  etl-script/test_transform.py
  etl-script/transform.py
  requirements.txt
Labels: enhancement

#48 adding utility scripts
  long-term-storage/activate_venv.sh
  long-term-storage/connect_to_db.sh
Labels: enhancement

#50 changed transform.py and added a test for email_alert
  etl-script/email_alert.py
  etl-script/test_email_alert.py
  etl-script/transform.py
Labels: enhancement

#71 transform now doesnt take in negative temperatures
  etl-script/transform.py
Labels: enhancement

#74 Terraform #36
  .gitignore
  terraform/main_etl.tf
  terraform/main_storage.tf
  terraform/output.tf
  terraform/provider.tf
  terraform/variables.tf
Labels: enhancement

#78 Why are negatives coming through
  .gitignore
  README.md
  activate_venv.sh
  connect_to_db.sh
  etl-script/README.md
  etl-script/email_alert.py
  etl-script/test_transform.py
  etl-script/transform.py
  long-term-storage/README.md
  schema/README.md
  terraform/README.md
  terraform/variables.tf
Labels: enhancement

#85 updated readme
  README.md
  requirements.txt
Labels: documentation

#87 added some missing docstrings #86
  long-term-storage/test_storage_load.py
Labels: documentation, enhancement
